
04:41:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:43:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:50:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:53:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:53:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:54:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:55:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:58:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:58:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

04:58:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:39
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(26): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:02:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/core/User.php:45
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/model/Users.php(67): core\User->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(54): model\Users->login(Array, Object(model\Sessions), Object(core\Request))
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:02:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/core/User.php:45
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/model/Users.php(67): core\User->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(54): model\Users->login(Array, Object(model\Sessions), Object(core\Request))
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:02:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/core/User.php:49
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/model/Users.php(67): core\User->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(54): model\Users->login(Array, Object(model\Sessions), Object(core\Request))
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:02:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/core/User.php:49
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/model/Users.php(67): core\User->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(54): model\Users->login(Array, Object(model\Sessions), Object(core\Request))
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:02:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/core/User.php:49
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/model/Users.php(67): core\User->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(54): model\Users->login(Array, Object(model\Sessions), Object(core\Request))
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:02:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/core/User.php:49
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/model/Users.php(67): core\User->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(54): model\Users->login(Array, Object(model\Sessions), Object(core\Request))
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:03:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/core/User.php:49
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/model/Users.php(67): core\User->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(54): model\Users->login(Array, Object(model\Sessions), Object(core\Request))
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:03:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/core/User.php:49
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/model/Users.php(67): core\User->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(54): model\Users->login(Array, Object(model\Sessions), Object(core\Request))
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:16:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:70
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(50): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

05:16:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(50): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(44): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

06:53:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/BaseModel.php:45
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/controller/PostController.php(89): model\BaseModel->add(Array)
#1 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\PostController->addAction()
#2 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#3 {main}
-------------------------------------------------------------------------------------

06:54:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(48): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

07:07:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:70
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(48): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

13:39:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:64
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(48): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

13:52:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:64
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(48): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

13:52:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(48): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

13:53:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(48): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:04:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(50): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:07:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:64
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(50): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:14:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(50): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:15:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:70
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(50): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:15:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:70
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(50): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:16:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:19:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:36
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(21): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:20:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:36
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(37): model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(21): core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:27:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:29:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:33:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:38:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:40:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:40:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:41:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:42:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:43:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

14:45:11
::1

core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/model/Users.php:74
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/core/User.php(42): model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/controller/UserController.php(46): core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/core/Application.php(46): controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(8): core\Application->run()
#4 {main}
-------------------------------------------------------------------------------------

23:48:11
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/BaseModel.php:45
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Controller/PostController.php(78): NTSchool\Phpblog\Model\BaseModel->add(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Core/Core.php(41): NTSchool\Phpblog\Controller\PostController->addAction()
#2 /Applications/MAMP/htdocs/blog-php3/index.php(3): NTSchool\Phpblog\Core\Core->run()
#3 {main}
-------------------------------------------------------------------------------------

23:55:11
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:64
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(42): NTSchool\Phpblog\Model\Users->login(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(42): NTSchool\Phpblog\Core\User->login(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Core/Core.php(41): NTSchool\Phpblog\Controller\UserController->loginAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(3): NTSchool\Phpblog\Core\Core->run()
#4 {main}
-------------------------------------------------------------------------------------

23:55:11
::1

NTSchool\Phpblog\Core\Exceptions\ValidateException: validation exception in /Applications/MAMP/htdocs/blog-php3/app/Model/Users.php:36
Stack trace:
#0 /Applications/MAMP/htdocs/blog-php3/app/Core/User.php(37): NTSchool\Phpblog\Model\Users->signUp(Array)
#1 /Applications/MAMP/htdocs/blog-php3/app/Controller/UserController.php(19): NTSchool\Phpblog\Core\User->signUp(Array)
#2 /Applications/MAMP/htdocs/blog-php3/app/Core/Core.php(41): NTSchool\Phpblog\Controller\UserController->signUpAction()
#3 /Applications/MAMP/htdocs/blog-php3/index.php(3): NTSchool\Phpblog\Core\Core->run()
#4 {main}
-------------------------------------------------------------------------------------
